name: Delete Workflow Runs

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  delete-runs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Delete all workflow runs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get all workflow runs
        response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100")

        # Check if the response contains workflow runs
        if echo "$response" | jq -e '.workflow_runs' > /dev/null; then
          runs=$(echo "$response" | jq -r '.workflow_runs[].id')

          # Delete each workflow run
          for run_id in $runs; do
            echo "Deleting workflow run $run_id"
            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
          done
        else
          echo "No workflow runs found or failed to fetch workflow runs."
          echo "Response: $response"
        fi